defaults:
  - cvapipe_analysis_config: matheus_config
  - callbacks: callbacks
  - data: data
  - data/input: dna_coeffs
  - data/dir: mem_align_no_skew
  # - data/dir: dna_align_skew
  - data/set_zero: is_false
  - data/condition: dna_pca
  - network: network
  - network/hidden_layers: 1
  - network/architecture: baseline
  - training: training
  - training/batch_size: 128
  - hydra/launcher: joblib

hydra:
  run:
    dir: outputs/${hydra.job.override_dirname}
  sweep:
    dir: multirun/
    subdir: ${hydra.job.override_dirname}