defaults:
  - cvapipe_analysis_config: matheus_config
  - callbacks: callbacks
  - data: data
  - data/input: dna_coeffs
  - data/dir: mem_align_no_skew
  # - data/dir: dna_align_skew
  - data/set_zero: is_true
  - data/condition: dna_pca
  - network: network
  - network/hidden_layers: 1
  - network/architecture: baseline
  - training: training
  - training/batch_size: 128
  - hydra/launcher: joblib
  # - hydra/job_logging: colorlog
  # - hydra/hydra_logging: colorlog


hydra:
  run:
    dir: output_tmp_test/${hydra.job.override_dirname}
  sweep:
    dir: multirun_apr_14/
    subdir: ${hydra.job.override_dirname}