defaults:
  - _self_

output_root: /tmp/serotiny_${uuid:}

hydra:
  run:
    dir: ${output_root}/${task}/${now:%Y-%m-%d}/${now:%H-%M-%S_%f}
  sweep:
    dir: ${output_root}/${task}/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S_%f}
