_target_: pytorch_lightning.Trainer
max_epochs:
gpus:
# checkpoint_callback:
#   _target_: pytorch_lightning.callbacks.ModelCheckpoint
#   dirpath: 
enable_checkpointing: True
logger: 
  _target_: pytorch_lightning.loggers.MLFlowLogger
  experiment_name: test
  run_name: run_1
  tracking_uri: /allen/aics/modeling/ritvik/projects/bvae_nucmorph/results/