# example dummy model

_target_: serotiny.models.BasicModel

x_label: 0
y_label: 1

network:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.LazyConv2d
      out_channels: 3
      kernel_size: 3
    - _target_: torch.nn.MaxPool2d
      kernel_size: 3
    - _target_: torch.nn.LeakyReLU

    - _target_: torch.nn.LazyConv2d
      out_channels: 3
      kernel_size: 3
    - _target_: torch.nn.MaxPool2d
      kernel_size: 3
    - _target_: torch.nn.LeakyReLU

    - _target_: serotiny.networks.layers.Flatten
    - _target_: torch.nn.LazyLinear
      out_features: 10
    - _target_: torch.nn.LogSoftmax

loss:
  _target_: torch.nn.NLLLoss

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
