---
name: publish-dev
on:
  push:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: 3.8

      - name: Build package
        run: |
          pip install pdm-version && \
          pdm version "$(pdm show --version).dev$(date '+%Y%m%d%H%M')" && \
          pdm build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
